/*
-- Query: SELECT * FROM wadeadamdb.orders
LIMIT 0, 1000

-- Date: 2026-02-03 11:52
*/
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (1,'3200002','ADEL OFFICE EQUIP TRDG (LLC)','3','251962','1','5');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (2,'3200001','AFIF SARIUDDIN','3','20600','1','7');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (3,'3200003','ADIL & SADIQ SEAT MNFG. C','3','3425','1','8');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (4,'3200016','AL RAMA INT\'L TRDG(LLC)','2','2161913310','4','1');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (5,'3200049','AL MANHAL GENERAL LAND TR','1','22229500','5 ','2');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (6,'3200029','ARABIAN AUTOMOBILES','1','1100125','5','3');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (7,'3200019','AL SHAFAR TRANSP.&CONTG.','1','679976','5','4');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (8,'3200004','AL ABBAS TRADING CO.','1','137060','5','6');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (9,'3200064','AL WASL MACHINERY&SPARE P','1','900','5','9');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (10,'3200017','SKY WARDS GENERAL LAND TRP','1','800','5','10');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (11,'3200006','AL FUTTAIM AUTO CENTERS LLC','1','250','5','11');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (12,'320A122','ADVANCED LABORATARY CENTER LLC','1','212','5','13');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (13,'3200028','ARAB ORIENT INSURANCE CO.','1','150','5','13');
INSERT INTO `` (`SR.NO`,`SUPPLIER CODE`,`SUPPLIER NAME`,`TOTAL`,`VALUE`,`RANK BY ORDERS`,`RANK BY VALUE`) VALUES (14,'320T113','TOP LINK CRUSHER L.L.C.','1','120','5','14');
